<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE red [
<!ELEMENT red (centro)*>
<!ELEMENT centro (nombre, grado, anyo, localizacion)>
<!ATTLIST centro type CDATA #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT grado (#PCDATA)>
<!ELEMENT anyo (#PCDATA)>
<!ELEMENT localizacion (ciudad, comunidad)>
<!ELEMENT comunidad (#PCDATA)>
<!ELEMENT ciudad (#PCDATA)>
]>

<red>
  <centro type="Instituto">
    <nombre>IES Gran Capitán</nombre>
    <grado>Desarrollo de Aplicaciones Web</grado>
    <anyo>2020</anyo>
    <localizacion>
      <ciudad>Córdoba</ciudad>
      <comunidad>Andalucía</comunidad>
    </localizacion>
  </centro>
  <centro type="Instituto">
    <nombre>IES Gran Capitán</nombre>
    <grado>Desarrollo de Aplicaciones Web</grado>
    <anyo>2020</anyo>
    <localizacion>
      <ciudad>Córdoba</ciudad>
      <comunidad>Andalucía</comunidad>
    </localizacion>
  </centro>
</red>

